version: '2'
services:
  fc20071401-app:
    image: fc20071401
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fc20071401-postgresql:5432/fc20071401
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  fc20071401-postgresql:
    extends:
      file: postgresql.yml
      service: fc20071401-postgresql
